### ISSUE TITLE
Make a setting for the sound feedback

### ISSUE THREAD

**Issue by flodieder** [dotscene-gmbh/dotcube-app#16]
### Description
The sound feedback that will be integrated into the dotcube should be controllable from the app.

### To-Do
- [x] Add a sound settings menu entry
- [x] Add a persistent setting
- [x] Add sound setting to the dotcube <-> app protocol

**Comment by flodieder** [comment]
Was part of v1.3.0
